### PR TITLE
MK - Nav bar

### PR DESCRIPTION
**Pull request by Mikikahana**
Added NavBar with onClick on the words, Added correct icons and proper community logo

### CODE REVIEW

**Review by Irishwolf13 — CHANGES_REQUESTED** [review]
You want to merge this into develop, not into main.

I'll check out the changes after you fix that.
cheers,
Rooney

**Comment by sheenasany** [comment]
> You want to merge this into develop, not into main.
> 
> I'll check out the changes after you fix that. cheers, Rooney

**Review by sheenasany — CHANGES_REQUESTED** [review]
Nice, thank you changing the branch, btw. 
Another suggestion to change, which is minor, is the fact that your NavBarPage is actually considered a component and should placed within the components folder rather than under the pages folder. Double check the imports when you make those changes. 
I can merge once those changes are made.

**Review by sheenasany — APPROVED** [review]
Thanks for making the changes!

**Review by Irishwolf13 — APPROVED** [review]

**Comment by sheenasany** [comment]
> You want to merge this into develop, not into main.
> 
> I'll check out the changes after you fix that. cheers, Rooney

Awesome! Thanks!

**Pull request merged**
